### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/song-helper#15]
### Tasks

- [x] Create _better_ README.md (**18.02**)
- [x] Create CONTRIBUTING.md and CODE_OF_CONDUCT.md (**21.02**)

> some tasks will add later

### Literature

- [My Templates](https://github.com/mezgoodle/Templates)
- [Your Templates](https://github.com/VsIG-official/README-Template)

### Branch

[master](https://github.com/mezidia/song-helper)

### Folder

[root](https://github.com/mezidia/song-helper)

**Comment by mezgoodle** [comment]
Now I have a problem with adding this repository to [Codacy](https://app.codacy.com/), but I'll try to solve it. If everything is good, I'll notice you.

**Comment by mezgoodle** [comment]
@VsIG-official 
As you can see, Codacy already works. I'll do some magic so we have the highest score.

- In lines [5](https://github.com/mezidia/song-helper/blob/master/README.md#L5)-[10](https://github.com/mezidia/song-helper/blob/master/README.md#L10)(README.md) change in links `Templates` to `song-helper`
- Move Codacy badge to _Code style_ paragraph
- [Site](http://toc-generator.herokuapp.com/) for TOC generating
- Look at this [tasks](https://drive.google.com/drive/folders/1ofgWaSGE8bwiAJEG26Gr_cz9soiaoxrZ), maybe something need to changing. It will be better, if we can discuss these tasks in [Discussions](https://github.com/mezidia/song-helper/discussions/5)
- If you have questions about Templates, write here or in Discussions

> Maybe you wanted to work with these problems I wrote earlier, so I apologize

**Comment by mezgoodle** [comment]
@VsIG-official 

- Badge on the [line 77](https://github.com/mezidia/song-helper/blob/master/README.md#L77) is unnecessary, you can remove it.
- In paragraph [Build status](https://github.com/mezidia/song-helper/blob/master/README.md#L69) you can add these badges:

```
[![Bot CI](https://github.com/mezidia/song-helper/actions/workflows/bot.yml/badge.svg)](https://github.com/mezidia/song-helper/actions/workflows/bot.yml)
[![Formate Code](https://github.com/mezidia/song-helper/actions/workflows/formatter.yml/badge.svg)](https://github.com/mezidia/song-helper/actions/workflows/formatter.yml)
[![song-helper CI](https://github.com/mezidia/song-helper/actions/workflows/song-helper.yml/badge.svg)](https://github.com/mezidia/song-helper/actions/workflows/song-helper.yml)
[![Django CI](https://github.com/mezidia/song-helper/actions/workflows/django.yml/badge.svg)](https://github.com/mezidia/song-helper/actions/workflows/django.yml)
```

- In paragraph [Tech/framework used :wrench:](https://github.com/mezidia/song-helper/blob/master/README.md#L83) add this text:

```
- [NumPy](https://numpy.org/)
- [TensorFlow](https://www.tensorflow.org/)
- [aiogram](https://github.com/aiogram/aiogram)
- [python-dotenv](https://pypi.org/project/python-dotenv/)
```
In paragraph [Tests :microscope:](https://github.com/mezidia/song-helper/blob/master/README.md#L105) add this text:
```
We use [unittest](https://docs.python.org/3/library/unittest.html) as framework for testing. All results you can see [here](https://github.com/mezidia/song-helper/actions). For tests look in folders of each part of this project.
```
All your done work is very good!

**Comment by VsIG-official** [comment]
Done

**Comment by mezgoodle** [comment]
> Done

THE BEST!

**Comment by mezgoodle** [comment]
> Done

Issue with _Django.yml_ badge is normal. It's because Django CI hasn't started even

**Comment by VsIG-official** [comment]
Finish the second item

**Comment by mezgoodle** [comment]
> Finish the second item

Perfect!
