### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/song-helper#213]
@MaksGovor, please write, which endpoints you need from the server. We can make a call

**Comment by MaksGovor** [comment]
## 1
I think we'll need to authorize on the server to ensure security against bots, so it can be endpoints for authorization/registration, or we can integrate a third-party [Identity Provider](https://www.g2.com/categories/identity-and-access-management-iam/free), but in any case, we'll have some information about users in the database and we'll need a basic CRUD set for the user profile.

## 2
It will also be a cool feature to store the user's request history, which requires two endpoints:
- delete history record by id
- get multiple history records by user id, offset, and limit (for pagination)

** adding automatically when a new song is requested

## 3
And in general, to request a new song, we need a POST request to get a response for a given promt. 

This is all that came to mind so far, we will continue to expand :)

**Comment by mezgoodle** [comment]
> ## 1
> I think we'll need to authorize on the server to ensure security against bots, so it can be endpoints for authorization/registration, or we can integrate a third-party [Identity Provider](https://www.g2.com/categories/identity-and-access-management-iam/free), but in any case, we'll have some information about users in the database and we'll need a basic CRUD set for the user profile.
> 
> ## 2
> It will also be a cool feature to store the user's request history, which requires two endpoints:
> 
> * delete history record by id
> * get multiple history records by user id, offset, and limit (for pagination)
> 
> ** adding automatically when a new song is requested
> 
> ## 3
> And in general, to request a new song, we need a POST request to get a response for a given promt.
> 
> This is all that came to mind so far, we will continue to expand :)

So, I came to this:

| Router      | Endpoint |
| ----------- | ----------- |
| _users_      | |
| | create(register) ✅|
| | login(token) ✅ |
| | update itself ✅ |
| | delete itself ✅ |
| | get ✅ |
| | get all ✅ |
| | get me ✅ |
| _requests_      | |
| | delete by id ✅ |
| | get requests by user id with offset and limit ✅|
| | create request ✅|
| _songs_      | |
| | make a promt✅ |

If we will have something new in future it will be easier to add.

Thank you!
